# NumPy
---

* Numeric Python
* Paquete fundamental para cómputo científico en Python
* Realizar cálculos estadísticos y matemáticos
* Para analizar grandes volumenes de datos numéricos
* Provee un tipo de datos (similar a las listas): NumPy Array
* Los arrays de NumPy deben ser homogéneos (valores del mismo tipo)
* Eficiencia
* [Documentación](https://numpy.org/doc/2.2/index.html)

In [1]:
# altura en metros de personas
alturas = [1.73, 1.68, 1.71, 1.89, 1.79, 1.76, 1.67]

# peso en Kg de personas
pesos = [65.4, 59.2, 63.6, 88.4, 68.7, 89.7, 73.2]

# imc = pesos_personas_en_kg / (alturas_personas_en_metros ** 2)

## Sin NumPy

In [2]:
persona = 0
for altura in alturas:
    peso = pesos[persona]
    imc = round(peso / (altura ** 2), 8)
    print(imc)
    persona = persona + 1

21.85171573
20.97505669
21.75028214
24.7473475
21.44127836
28.95790289
26.24690738


## Con NumPy

In [3]:
!pip install numpy

In [4]:
import numpy as np

array_alturas = np.array(alturas)
array_pesos = np.array(pesos)

imc = array_pesos / (array_alturas ** 2)
imc

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836,
       28.95790289, 26.24690738])

In [5]:
type(imc)

numpy.ndarray

In [6]:
numpy_array_1 = np.array([True, 1, 2])   # True es 1
numpy_array_2 = np.array([3, 4, False])  # False es 0
numpy_array_1 + numpy_array_2

array([4, 5, 2])

In [7]:
python_list = [1, 2, 3]
numpy_array = np.array([1, 2, 3])
print(python_list + python_list)
print(numpy_array + numpy_array)

[1, 2, 3, 1, 2, 3]
[2 4 6]


## Creación de ndarray

In [8]:
numeros_primos = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29]
array_primos = np.array(numeros_primos)
array_primos

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29])

In [9]:
array_zeros = np.zeros(10)
array_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
array_unos = np.ones(10)
array_unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
array_numeros = np.arange(10)
array_numeros

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
array_pares = np.arange(0, 20, 2)
array_pares

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## Subconjuntos / Slices

In [13]:
imc < 28

array([ True,  True,  True,  True,  True, False,  True])

In [14]:
# subsetting / slicing numpy arrays
imc [imc < 28]

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836,
       26.24690738])

## Arrays NumPy de una dimensión (1D)

In [15]:
type(imc)

numpy.ndarray

In [16]:
imc.shape

(7,)

In [17]:
imc.ndim

1

## Cálculos con arrays 1D

In [18]:
array_impares = array_pares + 1
array_impares

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [19]:
# multiplicar por 100
array_impares * 100

array([ 100,  300,  500,  700,  900, 1100, 1300, 1500, 1700, 1900])

In [20]:
# restar entre arrays
array_impares - array_pares

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## Arrays NumPy de dos dimensiones (2D)

In [21]:
numpy_2d = np.array([alturas, pesos])
numpy_2d

array([[ 1.73,  1.68,  1.71,  1.89,  1.79,  1.76,  1.67],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 , 89.7 , 73.2 ]])

In [22]:
# (filas, columnas)
numpy_2d.shape

(2, 7)

In [23]:
numpy_2d.ndim

2

In [24]:
# seleccionar un elemento
numpy_2d[0][2]

1.71

In [25]:
# seleccionar un elemento
numpy_2d[0, 2]

1.71

In [26]:
# seleccionar todas las columnas de la fila 1
numpy_2d[1, :]

array([65.4, 59.2, 63.6, 88.4, 68.7, 89.7, 73.2])

In [27]:
# seleccionar todas las filas de la columna 1
numpy_2d[:, 1]

array([ 1.68, 59.2 ])

In [28]:
# seleccionar todas las filas de las columnas 1 y 2 (3 es excluyente)
numpy_2d[:, 1:3]

array([[ 1.68,  1.71],
       [59.2 , 63.6 ]])

In [29]:
# utilizar filter: menores de 1.70
numpy_2d[numpy_2d < 1.70]

array([1.68, 1.67])

## Cálculos con arrays 2D

In [30]:
np_matriz = np.array([[1, 2], [3, 4], [5, 6]])
np_matriz.ndim

2

In [31]:
np_matriz * 2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [32]:
np_matriz + np.array([10, 12])

array([[11, 14],
       [13, 16],
       [15, 18]])

In [33]:
np_matriz + np_matriz

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

## Transposiciones

In [34]:
array_simple = np.array([[0, 1], [2, 3], [4, 5]])
array_simple_transpuesto = np.transpose(array_simple)
array_simple_transpuesto

array([[0, 2, 4],
       [1, 3, 5]])

In [35]:
array_simple.shape

(3, 2)

In [36]:
array_simple_transpuesto.shape

(2, 3)

## Pedir información con NumPy

[numpy.transpose](https://numpy.org/doc/2.2/reference/generated/numpy.transpose.html)

In [37]:
np.info(np.transpose)

Returns an array with axes transposed.

For a 1-D array, this returns an unchanged view of the original array, as a
transposed vector is simply the same vector.
To convert a 1-D array into a 2-D column vector, an additional dimension
must be added, e.g., ``np.atleast2d(a).T`` achieves this, as does
``a[:, np.newaxis]``.
For a 2-D array, this is the standard matrix transpose.
For an n-D array, if axes are given, their order indicates how the
axes are permuted (see Examples). If axes are not provided, then
``transpose(a).shape == a.shape[::-1]``.

Parameters
----------
a : array_like
    Input array.
axes : tuple or list of ints, optional
    If specified, it must be a tuple or list which contains a permutation
    of [0,1,...,N-1] where N is the number of axes of `a`. The `i`'th axis
    of the returned array will correspond to the axis numbered ``axes[i]``
    of the input. If not specified, defaults to ``range(a.ndim)[::-1]``,
    which reverses the order of the axes.

Returns
-------

## Estadística básica

[Documentación de ndarray](https://numpy.org/doc/2.2/reference/generated/numpy.ndarray.html#numpy.ndarray)

In [38]:
valores = np.array([100, 200, 200, 250, 600])

In [39]:
# suma
valores.sum()

1350

In [40]:
# media o promedio
valores.mean()

270.0

In [41]:
# mínimo
valores.min()

100

In [42]:
# máximo
valores.max()

600

In [43]:
# mediana: valor del punto medio
np.median(valores)

200.0

In [44]:
# desvio: cuanto se desvian los valores de la media en la distribución
# describe que tan dispersos están los valores
# si es baja -> números cerca del valor medio
# si es alta -> valores distribuidos en un rango más amplio
valores.std()

172.04650534085255

In [45]:
# varianza: indica que tan dispersos están los valores
valores.var()

29600.0

In [46]:
# percentiles: se usan para proporcionar un número que describe el valor al cual un 
# porcentaje determinado de los valores es inferior
ages = [5, 31, 43, 48, 50, 41, 7, 11, 15, 39, 80, 82, 32, 2, 8, 6, 25, 36, 27, 61, 31]

percentil75 = np.percentile(ages, 75)
percentil75 # La respuesta es 43, lo que significa que el 75 % de las personas tienen 43 años o menos

43.0

In [47]:
from scipy import stats

# moda: valor más común
moda = stats.mode(ages)
moda

ModeResult(mode=31, count=2)

## Coeficientes de correlación

In [86]:
# calcula el coeficiente de correlación de Pearson
# mide la correlación lineal entre dos variables x, y
# 1: si los datos están correlacionados (si x aumenta, entonces aumenta y)
np.corrcoef(numpy_2d[:, 0], numpy_2d[:, 1])

array([[1., 1.],
       [1., 1.]])

## Rangos

In [49]:
np.linspace(0, 15, num=5)

array([ 0.  ,  3.75,  7.5 , 11.25, 15.  ])

In [50]:
np.arange(0, 15, step=2)

array([ 0,  2,  4,  6,  8, 10, 12, 14])

## Ordenar

In [51]:
# ordenar un np array
array_fibonacci = np.array([55, 0, 144, 1, 21, 89, 5, 8, 13, 1, 34, 3, 2])

In [52]:
# orden ascendente
np.sort(array_fibonacci)

array([  0,   1,   1,   2,   3,   5,   8,  13,  21,  34,  55,  89, 144])

In [53]:
# orden descendente
-np.sort(-array_fibonacci)

array([144,  89,  55,  34,  21,  13,   8,   5,   3,   2,   1,   1,   0])

In [54]:
# ordenar un 2D np array sobre el primer eje (columnas)
a = np.array([[10, 40, 30, 20],[30, 20, 10, 40]])
np.sort(a, axis=0)

array([[10, 20, 10, 20],
       [30, 40, 30, 40]])

In [55]:
# ordenar un 2D np array sobre el último eje (filas)
np.sort(a, axis=1)

array([[10, 20, 30, 40],
       [10, 20, 30, 40]])

In [56]:
# aplanar y ordenar
np.sort(a, axis=None)

array([10, 10, 20, 20, 30, 30, 40, 40])

## Ejemplo: muestra poblacional

In [57]:
poblacion = np.genfromtxt('muestra_poblacional.csv', delimiter=",")
poblacion

array([[ 1.97, 69.67],
       [ 1.77, 99.96],
       [ 1.68, 49.81],
       ...,
       [ 1.57, 51.63],
       [ 1.74, 50.88],
       [ 1.77, 90.25]])

In [58]:
type(poblacion)

numpy.ndarray

In [59]:
poblacion.shape

(5000, 2)

In [60]:
poblacion.ndim

2

In [61]:
poblacion[:, 1]

array([69.67, 99.96, 49.81, ..., 51.63, 50.88, 90.25])

In [62]:
poblacion[:, 0]

array([1.97, 1.77, 1.68, ..., 1.57, 1.74, 1.77])

In [63]:
poblacion[:10, :]

array([[ 1.97, 69.67],
       [ 1.77, 99.96],
       [ 1.68, 49.81],
       [ 1.88, 68.13],
       [ 1.83, 47.57],
       [ 2.02, 32.46],
       [ 1.89, 65.5 ],
       [ 1.72, 92.28],
       [ 1.76, 40.56],
       [ 2.05, 78.01]])

In [64]:
# promedio altura
promedio_alt = np.mean(poblacion[:, 0])
promedio_alt

1.7484019999999998

In [65]:
# promedio peso
promedio_peso = np.mean(poblacion[:, 1])
promedio_peso

60.43528200000001

In [66]:
# mínimo altura
minimo_alt = np.min(poblacion[:, 0])
minimo_alt

1.07

In [67]:
# mínimo peso
minimo_peso = np.min(poblacion[:, 1])
minimo_peso

-2.22

In [68]:
# máximo altura
maximo_alt = np.max(poblacion[:, 0])
maximo_alt

2.43

In [69]:
# máximo peso
maximo_peso = np.max(poblacion[:, 1])
maximo_peso

107.7

In [70]:
# mediana altura
mediana_altura = np.median(poblacion[:, 0])
mediana_altura

1.74

In [71]:
# mediana peso
mediana_peso = np.median(poblacion[:, 1])
mediana_peso

60.394999999999996

In [72]:
# desvio
np.std(poblacion[:, 0])

0.19659538752473316

In [73]:
# varianza
np.var(poblacion[:, 0])

0.038649746396

In [77]:
# ordenar los datos por altura
altura_ordenada = np.sort(poblacion[:, 0])
altura_ordenada

array([1.07, 1.1 , 1.1 , ..., 2.39, 2.42, 2.43])

In [78]:
# ordenar los datos por peso
peso_ordenado = np.sort(poblacion[:, 1])
peso_ordenado

array([ -2.22,   7.91,   9.37, ..., 106.95, 107.4 , 107.7 ])

In [80]:
# filtro 
peso_ordenado > 0

array([False,  True,  True, ...,  True,  True,  True])

In [82]:
poblacion_filtrada = poblacion[poblacion[:, 1] > 0]
poblacion_filtrada.shape

(4999, 2)

In [85]:
# donde se encuentra un determinado valor
np.where(poblacion_filtrada[:, 1] == 50.88)

(array([4997]),)

In [87]:
# coeficientes de correlación
np.corrcoef(poblacion[:, 0], poblacion[:, 1])

array([[ 1.        , -0.00615188],
       [-0.00615188,  1.        ]])

## Cambiar la forma de un arreglo

In [88]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [91]:
b = a.reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [93]:
b_aplanado = b.flatten()
b_aplanado

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [95]:
filas, columnas = b.shape
filas

3

## Arrays con distintos tipos de datos

In [98]:
tipos = [('nom', 'S15'), ('ape', 'S15'), ('com', int), ('nota', float)]
alumnos = [('pablo', 'pandolfo', 1, 10.0),
           ('maria', 'garcia', 2, 8.0), 
           ('ana', 'perez', 2, 5.0)]

alumnos = np.array(alumnos, dtype=tipos)
alumnos

array([(b'pablo', b'pandolfo', 1, 10.), (b'maria', b'garcia', 2,  8.),
       (b'ana', b'perez', 2,  5.)],
      dtype=[('nom', 'S15'), ('ape', 'S15'), ('com', '<i8'), ('nota', '<f8')])

In [99]:
np.sort(alumnos, order='ape')

array([(b'maria', b'garcia', 2,  8.), (b'pablo', b'pandolfo', 1, 10.),
       (b'ana', b'perez', 2,  5.)],
      dtype=[('nom', 'S15'), ('ape', 'S15'), ('com', '<i8'), ('nota', '<f8')])

In [100]:
np.sort(alumnos, order='nota')

array([(b'ana', b'perez', 2,  5.), (b'maria', b'garcia', 2,  8.),
       (b'pablo', b'pandolfo', 1, 10.)],
      dtype=[('nom', 'S15'), ('ape', 'S15'), ('com', '<i8'), ('nota', '<f8')])

## Ejercicio

In [104]:
ansur = np.genfromtxt('ANSUR_Femal.csv', delimiter=",", skip_header=1)
ansur

array([[1.00370e+04, 2.31000e+02, 1.28200e+03, ..., 6.10000e+01,
        1.42000e+02,         nan],
       [1.00380e+04, 1.94000e+02, 1.37900e+03, ..., 6.40000e+01,
        1.20000e+02,         nan],
       [1.00420e+04, 1.83000e+02, 1.36900e+03, ..., 6.80000e+01,
        1.47000e+02,         nan],
       ...,
       [2.95030e+04, 2.60000e+02, 1.33400e+03, ..., 6.60000e+01,
        1.68000e+02,         nan],
       [2.95110e+04, 2.05000e+02, 1.29300e+03, ..., 6.30000e+01,
        1.33000e+02,         nan],
       [9.20103e+05, 2.38000e+02, 1.34600e+03, ..., 6.60000e+01,
        1.32000e+02,         nan]])

In [105]:
ansur.ndim

2

In [106]:
ansur.shape

(1986, 108)

In [112]:
peso = ansur[:, 91]
peso

array([657., 534., 663., ..., 762., 632., 610.])

In [114]:
estatura = ansur[:, 75]
estatura

array([1560., 1665., 1711., ..., 1644., 1616., 1641.])

In [119]:
print(f'Mínimo = {peso.min()}, Máximo = {peso.max()}, Promedio = {peso.mean()}')

Mínimo = 358.0, Máximo = 1196.0, Promedio = 677.5820745216515


In [120]:
print(f'Mínimo = {estatura.min()}, Máximo = {estatura.max()}, Promedio = {estatura.mean()}')

Mínimo = 1409.0, Máximo = 1829.0, Promedio = 1628.4733131923465


In [115]:
np.corrcoef([peso, estatura])

array([[1.        , 0.53347308],
       [0.53347308, 1.        ]])